landmarks:
  stop_1:
    x: -1.958
    y: 2.970
    yaw: 0.0
  stop_2:
    x: -13.306
    y: 2.087
    yaw: 0.0
  stop_3:
    x: -8.397
    y: 4.337
    yaw: 0.0
  stop_4:
    x: -4.829
    y: 10.130
    yaw: 0.0
  stop_5:
    x: -0.962
    y: 4.215
    yaw: 0.0
  stop_6:
    x: 1.962
    y: 2.784
    yaw: 0.0
  stop_7:
    x: -3.074
    y: 1.138
    yaw: 0.0
  stop_8:
    x: -6.994
    y: 2.391
    yaw: 0.0
