frame_id: map
landmarks:
  computer_door:     {x: 1.278, y: -0.001, yaw: 0.0}
  whiteboard_pillar: {x: -3.307, y: -0.001, yaw: 0.0}
  cardboard_corner:  {x: -1.579, y: -0.771, yaw: 0.0}
  room_center:       {x: -1.677, y: -5.819, yaw: 0.0}
  charging_stations: {x: 0.052, y: -6.446, yaw: 0.0}
  cardboard_room:    {x: -0.191, y: -2.924, yaw: 0.0}