frame_id: map
landmarks:
  computer_door:     {x: -2.002, y: -3.760, yaw: 0.0}
  whiteboard_pillar: {x: -6.389, y: -4.927, yaw: 0.0}
  cardboard_corner:  {x: -4.860, y: -5.134, yaw: 0.0}
  unnamed_stop:      {x: -5.270, y: -6.917, yaw: 0.0}
  charging_stations: {x: -2.714, y: -7.772, yaw: 0.0}
  cardboard_room:    {x: -3.930, y: -3.416, yaw: 0.0}